@startwbs
* Company
** Branch A
***_ Customers
****_ Customer A
****_ Customer B
****_ Customer C
****_ Customer D
****_ Customer E
***_ Projects
****_ Project A
****_ Project B
****_ Project C
****_ Project D
****_ Project E
** Branch B
***_ Customers
***_ Projects
** Branch C
***_ Customers
***_ Projects
** R&D
***_ AI
***_ Cloud
****_ Hyperscaler A
****_ Hyperscaler B
****_ Hyperscaler C
***_ Security
@endwbs
