@startuml

!include <tupadr3/common>

!include <tupadr3/devicons2/angularjs>
!include <tupadr3/devicons2/apache>
!include <tupadr3/devicons2/bash>
!include <tupadr3/devicons2/c>
!include <tupadr3/devicons2/chrome>
!include <tupadr3/devicons2/circleci>
!include <tupadr3/devicons2/clojure_line>
!include <tupadr3/devicons2/clojurescript>
!include <tupadr3/devicons2/csharp>
!include <tupadr3/devicons2/css3>
!include <tupadr3/devicons2/dart>
!include <tupadr3/devicons2/digitalocean>
!include <tupadr3/devicons2/django>
!include <tupadr3/devicons2/docker>
!include <tupadr3/devicons2/dot_net>
!include <tupadr3/devicons2/elixir>
!include <tupadr3/devicons2/elm>
!include <tupadr3/devicons2/erlang>
!include <tupadr3/devicons2/figma>
!include <tupadr3/devicons2/firebase>
!include <tupadr3/devicons2/flutter>
!include <tupadr3/devicons2/gatling>
!include <tupadr3/devicons2/gimp>
!include <tupadr3/devicons2/gitlab>
!include <tupadr3/devicons2/go>
!include <tupadr3/devicons2/graphql>
!include <tupadr3/devicons2/haskell>
!include <tupadr3/devicons2/heroku>
!include <tupadr3/devicons2/html5>
!include <tupadr3/devicons2/java>
!include <tupadr3/devicons2/javascript>
!include <tupadr3/devicons2/jenkins>
!include <tupadr3/devicons2/jquery>
!include <tupadr3/devicons2/julia>
!include <tupadr3/devicons2/jupyter>
!include <tupadr3/devicons2/kubernetes>
!include <tupadr3/devicons2/kotlin>
!include <tupadr3/devicons2/linux>
!include <tupadr3/devicons2/lua>
!include <tupadr3/devicons2/matlab>
!include <tupadr3/devicons2/microsoftsqlserver>
'!include <tupadr3/devicons2/nginx>
'!include <tupadr3/devicons2/nixos>
!include <tupadr3/devicons2/nodejs>
!include <tupadr3/devicons2/objectivec>
!include <tupadr3/devicons2/ocaml>
!include <tupadr3/devicons2/perl>
!include <tupadr3/devicons2/php>
!include <tupadr3/devicons2/postgresql>
!include <tupadr3/devicons2/r>
!include <tupadr3/devicons2/rails>
!include <tupadr3/devicons2/redis>
!include <tupadr3/devicons2/ruby>
!include <tupadr3/devicons2/rust>
!include <tupadr3/devicons2/scala>
!include <tupadr3/devicons2/spring>
!include <tupadr3/devicons2/swift>
!include <tupadr3/devicons2/tailwindcss>
!include <tupadr3/devicons2/typescript>
!include <tupadr3/devicons2/ubuntu>
!include <tupadr3/devicons2/vscode>
!include <tupadr3/devicons2/vuejs>


listsprites

@enduml
