@startuml deployment-model-elements






title Deployment Model Elements

class "node" as overarch_dataModel_node {}
class "artifact" as overarch_dataModel_artifact {}
abstract class "deployment-model-relation" as overarch_dataModel_deploymentModelRelation {}
class "link" as overarch_dataModel_link {}
abstract class "model-element" as overarch_dataModel_modelElement {
  maturity : keyword [0..1]
  tags : set [0..1]
}
class "deployed-to" as overarch_dataModel_deployedTo {}
abstract class "technical-element" as overarch_dataModel_technicalElement {
  tech : string [0..1]
}
class "version" as overarch_dataModel_version {}
class "artifact-of" as overarch_dataModel_artifactOf {}
abstract class "deployment-model-node" as overarch_dataModel_deploymentModelNode {}
abstract class "model-node" as overarch_dataModel_modelNode {}
abstract class "model-relation" as overarch_dataModel_modelRelation {
  from : keyword
  to : keyword
}
abstract class "deployment-model-element" as overarch_dataModel_deploymentModelElement {}
abstract class "element" as overarch_dataModel_element {
  desc : string [0..1]
  doc : string [0..1]
  el : keyword
  id : keyword
  name : string
}
class "container" as overarch_dataModel_container {}
overarch_dataModel_element <|-- overarch_dataModel_modelElement
overarch_dataModel_modelRelation <|-- overarch_dataModel_deploymentModelRelation
overarch_dataModel_modelElement <|-- overarch_dataModel_modelNode
overarch_dataModel_node *-->  "ct\n0..n" overarch_dataModel_deploymentModelNode
overarch_dataModel_modelElement <|-- overarch_dataModel_modelRelation
overarch_dataModel_deploymentModelElement <|-- overarch_dataModel_deploymentModelNode
overarch_dataModel_technicalElement <|-- overarch_dataModel_artifact
overarch_dataModel_deploymentModelRelation <|-- overarch_dataModel_deployedTo
overarch_dataModel_modelNode <|-- overarch_dataModel_deploymentModelNode
overarch_dataModel_technicalElement <|-- overarch_dataModel_deploymentModelElement
overarch_dataModel_modelElement <|-- overarch_dataModel_deploymentModelElement
overarch_dataModel_deploymentModelRelation <|-- overarch_dataModel_link
overarch_dataModel_deploymentModelNode <|-- overarch_dataModel_node
overarch_dataModel_deploymentModelNode <|-- overarch_dataModel_container
overarch_dataModel_deploymentModelElement <|-- overarch_dataModel_deploymentModelRelation
@enduml
