@startuml

!include <azure/AzureCommon.puml>

'!include <azure/AIMachineLearning/all.puml>
'!include <azure/Analytics/all.puml>
'!include <azure/Blockchain/all.puml>
'!include <azure/Compute/all.puml>
'!include <azure/Containers/all.puml>
'!include <azure/Databases/all.puml>
'!include <azure/Devops/all.puml>
'!include <azure/General/all.puml>
'!include <azure/Health/all.puml>
'!include <azure/Identity/all.puml>
'!include <azure/Integration/all.puml>
'!include <azure/InternetOfThings/all.puml>
'!include <azure/Intune/all.puml>
'!include <azure/Management/all.puml>
'!include <azure/Media/all.puml>
'!include <azure/Migrate/all.puml>
'!include <azure/Mobile/all.puml>
!include <azure/Networking/all.puml>
'!include <azure/Security/all.puml>
'!include <azure/Stack/all.puml>
'!include <azure/Storage/all.puml>
'!include <azure/Web/all.puml>


listsprites

@enduml
