@startuml container-view
!include <C4/C4_Container.puml>
!include <awslib14/AWSCommon>
!include <awslib14/AWSC4Integration>
!include <azure/AzureCommon>
!include <azure/AzureC4Integration>
!include <tupadr3/common>
!include <tupadr3/devicons/clojure>







title Container View of Overarch
System_Ext(overarch_architecture_editor, "Editor/IDE", $descr="Tool for describing the architecture model and the views.")
Person(overarch_roles_modeller, "Modeller", $descr="Models the architecture of a system and specifies views of the model.")
Person(overarch_roles_templateProgrammer, "Template Programmer", $descr="Creates templates for artifact generation.")
System_Ext(overarch_architecture_plantuml, "PlantUML", $descr="Tool for generating diagrams.")
System_Ext(overarch_architecture_graphviz, "Graphviz", $descr="Tool for generating graph layouts and diagrams.")
System_Boundary(overarch_architecture_overarch, "Overarch") {
  Container(overarch_architecture_overarchCli, "Overarch CLI", $descr="CLI tool for the generation of value from the knowledge.", $techn="Clojure", $sprite="clojure")
}
Rel(overarch_roles_templateProgrammer, overarch_architecture_editor, "programs in", $descr="creates templates")
Rel(overarch_roles_modeller, overarch_architecture_overarchCli, "uses", $descr="for diagram generation and model transformation.")
Rel(overarch_roles_modeller, overarch_architecture_editor, "models in", $descr="creates models and views")
SHOW_LEGEND()
@enduml
