@startuml deployment-view
!include <C4/C4_Deployment.puml>
!include <awslib14/AWSCommon>
!include <awslib14/AWSC4Integration>
!include <azure/AzureCommon>
!include <azure/AzureC4Integration>
!include <tupadr3/common>







title Deployment View for Overarch
Node(overarch_deployment_os, "Operating System", $descr="e.g. Linux, MacOS, Windows") {
  Node(overarch_deployment_jvm, "Java Virtual Machine", $descr="Java Virtual Machine") {
    Container(overarch_deployment_overarchCli, "Overarch CLI", $descr="")
  }
  Container(overarch_deployment_graphviz, "GraphViz", $descr="generates diagrams for text based graph descriptions.")
}
SHOW_LEGEND()
@enduml
